### ISSUE TITLE
_html.replace is not a function

### ISSUE THREAD

**Issue by onordgren** [jonkemp/list-stylesheets#4]
Hi, we are using inline-css as a dependency and got the following error after list-stylesheet was bumped to the latest version. It works with version 1.1.1, any idea what the problem could be? 
```
Unhandled rejection TypeError: __html.replace is not a function
    at /node_modules/list-stylesheets/index.js:27:33
    at Array.forEach (native)
    at encodeCodeBlocks (/node_modules/list-stylesheets/index.js:24:33)
    at encodeEntities (/node_modules/list-stylesheets/index.js:45:20)
    at module.exports (/node_modules/list-stylesheets/index.js:52:22)
    at module.exports (/node_modules/extract-css/index.js:11:16)
    at /node_modules/inline-css/lib/inlineContent.js:15:9
    at tryCatcher (/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/node_modules/bluebird/js/main/promise.js:71:37)
    at inlineContent (/node_modules/inline-css/lib/inlineContent.js:8:12)
    at /node_modules/inline-css/index.js:27:9
    at tryCatcher (/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/node_modules/bluebird/js/main/promise.js:71:37)
    at module.exports (/node_modules/inline-css/index.js:8:12)
```
```
├─┬ inline-css@2.2.5  
│ ├── bluebird@2.11.0 
│ ├─┬ cheerio@0.19.0 
│ │ ├─┬ css-select@1.0.0 
│ │ │ ├── css-what@1.0.0 
│ │ │ └── domutils@1.4.3 
│ │ └── lodash@3.10.1 
│ ├─┬ css-rules@1.0.3 
│ │ └── cssom@0.3.2 
│ ├── extend@3.0.1 
│ ├─┬ extract-css@1.0.5 
│ │ ├── batch@0.6.1 
│ │ ├─┬ href-content@1.0.3 
│ │ │ └─┬ remote-content@1.0.2 
│ │ │   └─┬ superagent@3.8.2 
│ │ │     ├── component-emitter@1.2.1 
│ │ │     ├── cookiejar@2.1.1 
│ │ │     ├── debug@3.1.0 
│ │ │     ├── formidable@1.1.1 
│ │ │     ├── methods@1.1.2 
│ │ │     ├── mime@1.6.0 
│ │ │     └─┬ readable-stream@2.3.5 
│ │ │       ├── isarray@1.0.0 
│ │ │       └── string_decoder@1.0.3 
│ │ ├─┬ list-stylesheets@1.2.0 
```

**Comment by jonkemp** [comment]
Please first make sure inline-css is updated to the latest, 2.3.0, before anything else. There is a problem but I've only seen it with the gulp plugin, gulp-inline-css so far.

**Comment by mrrotberry** [comment]
My version inline-css 2.3.0 and I have this problem with gulp plugin and gulp-inline-css plugin  now.

**Comment by jonkemp** [comment]
Fixes to the gulp plugin are being tracked here. 

https://github.com/jonkemp/gulp-inline-css/issues/50

For those that are having trouble with the plugin, I recommend using a lock file going forward which locks all your packages to a certain version and doesn't update them unless you tell it to.

**Comment by jonkemp** [comment]
Fix is available. 

https://github.com/jonkemp/gulp-inline-css/releases/tag/v3.1.3
